In [2]:
import numpy as np

In [3]:
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Arreglo: ", arr_rand)

Arreglo:  [8 8 3 7 7 0 4 2 5 2]


In [4]:
# Obtener índices (posiciones) en los que el valor sea > 5
indices_mayores_5 = np.where(arr_rand > 5)
print("Posiciones en donde el valor > 5:",indices_mayores_5)

Posiciones en donde el valor > 5: (array([0, 1, 3, 4]),)


In [5]:
arr_rand.take(indices_mayores_5)

array([[8, 8, 7, 7]])

In [6]:
arr_rand[indices_mayores_5]

array([8, 8, 7, 7])

In [7]:
print("Posición del elemento más grande (max):", np.argmax(arr_rand))
print("Posición del elemento más chico  (min):", np.argmin(arr_rand))

Posición del elemento más grande (max): 0
Posición del elemento más chico  (min): 5


In [8]:
#apagar la notación científica
np.set_printoptions(suppress=True)
ruta_url = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(ruta_url, delimiter=',', skip_header=1, filling_values=-999, dtype='float')
data[:3]

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
        -999. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
        -999. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
        -999. ]])

In [9]:
data2 = np.genfromtxt(ruta_url, delimiter=',', skip_header=1, dtype=None, encoding=None)
data2[:3]

array([(18., 8, 307., 130, 3504, 12. , 70, 1, '"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, '"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, '"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', '<U38')])

In [13]:
data3 = np.genfromtxt(ruta_url, delimiter=',', skip_header=1, dtype=float, filling_values=-999)
data3[:3]

array([[ 1.800e+01,  8.000e+00,  3.070e+02,  1.300e+02,  3.504e+03,
         1.200e+01,  7.000e+01,  1.000e+00, -9.990e+02],
       [ 1.500e+01,  8.000e+00,  3.500e+02,  1.650e+02,  3.693e+03,
         1.150e+01,  7.000e+01,  1.000e+00, -9.990e+02],
       [ 1.800e+01,  8.000e+00,  3.180e+02,  1.500e+02,  3.436e+03,
         1.100e+01,  7.000e+01,  1.000e+00, -9.990e+02]])

In [14]:
np.savetxt("out.csv", data3, delimiter=",")

In [1]:
import matplotlib.pyplot as plt

In [8]:
img = plt.imread('img/beagle.jpg')

In [9]:
img.shape

(1200, 1106, 3)

In [10]:
img.ndim

3

In [11]:
img[0,0]

array([255, 255, 157], dtype=uint8)

In [12]:
img[0,0]

array([255, 255, 157], dtype=uint8)

In [13]:
img2=plt.imread('img/salchicha.jpg')

In [14]:
img2.shape

(1414, 2121, 3)

In [ ]:
img2[0,0]