In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
np.all(a != 0)

np.True_

In [3]:
a = np.array([0, 0, 2, 0])
np.any(a != 0)

np.True_

In [4]:
a = np.array([1, 2, np.nan, np.inf])
contains_inf = np.any(np.isinf(a))
contains_nan = np.any(np.isnan(a))
contains_inf, contains_nan

(np.True_, np.True_)

In [5]:
a = np.array([1, 2, np.inf])
np.any(np.isinf(a))

np.True_

In [6]:
a = np.array([1, np.nan, 3])
np.any(np.isnan(a))

np.True_

In [7]:
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
(a > b, a >= b, a < b, a <= b)

(array([False, False,  True]),
 array([False,  True,  True]),
 array([ True, False, False]),
 array([ True,  True, False]))

In [8]:
arr = np.array([1, 7, 13, 105])
arr.nbytes

32

In [9]:
zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)
zeros, ones, fives

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [10]:
arr = np.arange(30, 71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [11]:
arr = np.arange(30, 71, 2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random()

0.28565381303238613

In [14]:
np.random.randn(15)

array([ 0.17690068,  0.04940813, -1.10085638,  0.29587602, -0.38059182,
        0.49957185,  0.3945067 ,  0.45675798,  0.6509531 , -1.03345099,
       -0.51610257,  0.15172076, -0.78699245, -0.38078419,  0.84111243])

In [15]:
arr = np.arange(15, 56)
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [16]:
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [17]:
v = np.arange(0, 21)
v[9:16] = -v[9:16]
v

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [18]:
a = np.array([1, 2, 3])
a.tolist()

[1, 2, 3]

In [19]:
l = [1, 2, 3]
np.array(l)

array([1, 2, 3])

In [20]:
m = np.array([[1, 2], [3, 4]])
evens = (m % 2 == 0)
evens

array([[False,  True],
       [False,  True]])

In [21]:
m = np.array([[1, 2, 3], [4, 5, 6]])
rows, cols = m.shape
rows, cols

(2, 3)